version: '3.8'
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - '80:80'   # Puerto HTTP para el proxy
      - '81:81'   # Puerto de la interfaz de administración de NPM
      - '443:443' # Puerto HTTPS para el proxy (SSL)
    volumes:
      - npm-data:/data
      - npm-config:/etc/nginx/conf.d
      - npm-letsencrypt:/etc/letsencrypt
    networks:
      - movie-reservation-network
    restart: always

  mysql-db:
    image: mysql:8.0

    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: user_service_db
      MYSQL_USER: user_app  # Nombre de usuario para la aplicación
      MYSQL_PASSWORD: password123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - movie-reservation-network
    restart: always

networks:
  movie-reservation-network:
    driver: bridge

volumes:
  npm-data:
  npm-config:
  npm-letsencrypt:
  mysql-data: